//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiemensProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlcDetail
    {
        public Nullable<int> PlcId { get; set; }
        public string SerialNo { get; set; }
        public string IpAddress { get; set; }
        public string Subnet { get; set; }
        public string Mlfb { get; set; }
        public string Firmware { get; set; }
        public string Mac_Address { get; set; }
        public string Operating_State { get; set; }
        public string Station_Name { get; set; }
        public string PLC_Name { get; set; }
        public string PLC_Type { get; set; }
        public string SMC_SerialNo { get; set; }
        public string Plant_DesignationId { get; set; }
        public string Location_Id { get; set; }
        public Nullable<bool> IsPingable { get; set; }
        public Nullable<bool> IsFaulty { get; set; }
    
        public virtual PlcInfo PlcInfo { get; set; }
        public string Rack_No { get; internal set; }
        public int? DeviceID { get; internal set; }
        public string Plc_SerialNo { get; internal set; }
    }
}
