//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiemensProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlcInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlcInfo()
        {
            this.PlcDetails = new HashSet<PlcDetail>();
        }
    
        public int PlcId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string IpAddress { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public string Rack_No { get; set; }
        public string Serial_No { get; set; }
        public string Comments { get; set; }
        public Nullable<int> AssetType_id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual PlcInfo PlcInfo1 { get; set; }
        public virtual PlcInfo PlcInfo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlcDetail> PlcDetails { get; set; }
    }
}
