//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiemensProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcssedWish
    {
        public int PWish_Id { get; set; }
        public Nullable<int> WishlistId { get; set; }
        public string RequestedDuration { get; set; }
        public string AvailableDuration { get; set; }
        public Nullable<System.DateTime> CommitedDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RemainingDays { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsNotifed { get; set; }
        public Nullable<bool> IsAcknowledged { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsRequestedReceived { get; set; }
        public Nullable<bool> IsExpired { get; set; }
    
        public virtual WishList WishList { get; set; }
    }
}
