//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiemensProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool
    {
        public int ToolId { get; set; }
        public string Description { get; set; }
        public Nullable<int> AssetType_Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string SerialNo { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual AssetType AssetType { get; set; }
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
