//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiemensProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishList
    {
        public int WishlistId { get; set; }
        public Nullable<int> WishTypeId { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> AssetTypeId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string RequestDuration { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsAcknowledged { get; set; }
        public Nullable<bool> IsMapped { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual AssetType AssetType { get; set; }
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
        public virtual WishListType WishListType { get; set; }
    }
}
