//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiemensProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishMapper
    {
        public int WishListId { get; set; }
        public Nullable<int> WishTypeId { get; set; }
        public string RequestedDuration { get; set; }
        public Nullable<int> UnassignedAsset_Id { get; set; }
        public string AvailableDuration { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsMapped { get; set; }
        public Nullable<bool> IsAcknowledged { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual WishList WishList { get; set; }
        public virtual WishListType WishListType { get; set; }
    }
}
